pipeline {
    agent any
    environment {
        IMAGE="docker.io/jimmytech/flask-pipe"
        TAG="${BUILD_NUMBER}"
    }
    stages {
        stage ('checkout') {
            steps {
                git branch: 'main', credentialsId: 'gith-pat', poll: false, url: 'https://github.com/jimmymuthoni/devops-with-jim.git'
            }      

        }
        stage ('build') {
            steps {
                sh 'docker build -t "$IMAGE:$TAG" -t "$IMAGE:latest" .'
            }      

        }
        stage ('push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'new-dockerhub', passwordVariable: 'DOCKERHUB_PWD', usernameVariable: 'DOCKERHUB_USER')]) {
                    sh 'echo "$DOCKERHUB_PWD" | docker login -u "$DOCKERHUB_USER" --password-stdin'
                    sh 'docker push "$IMAGE:$TAG"'
                    sh 'docker push "$IMAGE:latest"'

            }
                
            }      

        }
        stage ('deploy') {
            steps {
                sh 'docker pull "$IMAGE:$TAG"'
                sh 'docker rm -f flask-pipe || true'
                sh 'docker run -d --name flask-pipe -p 5000:5000 "$IMAGE:$TAG"'
            }      

        }
        stage ('test') {
            steps {
                sh 'sleep 2; echo "Hit http://localhost:5000 to see the app."'
            }      

        }

    }

}